[project]
name = "stock-buy-sell-signal-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "plotly>=6.1.2",
    "rich>=14.0.0",
    "streamlit>=1.45.1",
    "yahooquery>=2.4.1",
]
